### ISSUE TITLE
Error query after upgrade zabbix 5 to 6 for ldap

### ISSUE THREAD

**Issue by liyonia** [BGmot/zabbix#11]
Hello

need help after upgrade zabbix 5 to 6 

Cannot add LDAP group
    Error in query [INSERT INTO adusrgrp (adusrgrpid,name,roleid) VALUES ('5','GROUP','3')] [Unknown column 'roleid' in 'field list']
    SQL statement execution has failed "INSERT INTO adusrgrp (adusrgrpid,name,roleid) VALUES ('5','GROUP','3')".
    

LDAP groups
    Error in query [SELECT ag.adusrgrpid,ag.name,ag.roleid FROM adusrgrp ag ORDER BY ag.name LIMIT 1001] [Unknown column 'ag.roleid' in 'field list']
    Error in query [SELECT adg.adusrgrpid,r.name FROM adusrgrp adg,role r WHERE adg.roleid=r.roleid AND 1=0] [Unknown column 'adg.roleid' in 'where clause']
    
    
    Thank you in advance for your reply

**Comment by BGmot** [comment]
Hi,
on which Zabbix version are you getting this error? seems like db-update.sql did not execute properly.
Connect to your DB and execute following please
`describe adusrgrp;`

**Comment by liyonia** [comment]
Zabbix 6.0.0

I specify that the upgrade is 5.0.20 to 6.0.0
The script has been implemented in version 5.0.X

+------------+---------------------+------+-----+---------+-------+
| Field      | Type                | Null | Key | Default | Extra |
+------------+---------------------+------+-----+---------+-------+
| adusrgrpid | bigint(20) unsigned | NO   | PRI   | NULL      |       |
| name         | varchar(64)               | NO   | UNI  |                |       |
| user_type  | int(11)                       | NO   |         | 1             |       |
+------------+---------------------+------+-----+---------+-------+
3 rows in set (0.001 sec)

**Comment by BGmot** [comment]
You still have "old" DB schema for my features. Unfortunately I do not support 'upgrade' from 5.0 to 6.0.
Please Correct tables manually according to https://github.com/BGmot/zabbix/blob/release/6.0-bg/bg-scripts/db-update.sql

**Comment by BGmot** [comment]
I think you should modify db-update.sql script to:
```
CREATE TABLE `adusrgrp` (
        `adusrgrpid`             bigint unsigned                           NOT NULL,
        `name`                   varchar(64)     DEFAULT ''                NOT NULL,
        `roleid`                 bigint unsigned                            NOT NULL,
        PRIMARY KEY (adusrgrpid)
) ENGINE=InnoDB;
CREATE UNIQUE INDEX `adusrgrp_1` ON `adusrgrp` (`name`);
ALTER TABLE `adusrgrp` ADD CONSTRAINT `c_adusrgrp_1` FOREIGN KEY (`roleid`) REFERENCES `role` (`roleid`) ON DELETE CASCADE;
```
Then drop the table:
`drop adusrgrp`
And then execute db-update.sql script.
Should be enough but it will erase all your LDAP groups configuration. Let me know if you want to keep it.

**Comment by liyonia** [comment]
don't worry about it 

drop table adusrgrp;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails

it's ok after
SET FOREIGN_KEY_CHECKS=0; 
drop table adusrgrp;

**Comment by liyonia** [comment]
the script is halfway through

I had to delete
ALTER TABLE config ADD COLUMN 2fa_type INT(11) DEFAULT 0;
ALTER TABLE config ADD COLUMN 2fa_duo_api_hostname TINYTEXT;
ALTER TABLE config ADD COLUMN 2fa_duo_integration_key TINYTEXT;
ALTER TABLE config ADD COLUMN 2fa_duo_secret_key TINYTEXT;
ALTER TABLE config ADD COLUMN 2fa_duo_a_key TINYTEXT;

ALTER TABLE users ADD COLUMN ggl_secret VARCHAR(100) DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN ggl_enrolled INT DEFAULT 0 NOT NULL;


the connection is done well, but the page is blank right after

**Comment by BGmot** [comment]
Ah right.. foreing key... Then let's try this:
```
alter table adusrgrp drop column user_type;
alter table adusrgrp 'roleid' bigint unsigned default 1;
ALTER TABLE `adusrgrp` ADD CONSTRAINT `c_adusrgrp_1` FOREIGN KEY (`roleid`) REFERENCES `role` (`roleid`) ON DELETE CASCADE;
```

**Comment by BGmot** [comment]
> the connection is done well, but the page is blank right after

What page? What feature are you trying to use 2FA or AD groups?

**Comment by liyonia** [comment]
AD groups
 It recognizes the login and password, but there is no registration in the zabbix users

**Comment by BGmot** [comment]
Check apache/nginx logs. Did you apply the latest version of the script (for 6.0) https://raw.githubusercontent.com/BGmot/zabbix/6.0.0-bg/bg-scripts/bg-features-install.sh ?

**Comment by liyonia** [comment]
Yes, but apache2
PHP Fatal error:  Uncaught TypeError: array_key_exists() expects parameter 2 to be array, null given in /usr/share/zabbix/include/classes/api/CAudit.php:739\nStack trace:\n#0 /usr/share/zabbix/include/classes/api/CAudit.php(813): CAudit::isDefaultValue()\n#1 /usr/share/zabbix/include/classes/api/CAudit.php(587): CAudit::handleAdd()\n#2 /usr/share/zabbix/include/classes/api/CAudit.php(494): CAudit::handleObjectDiff()\n#3 /usr/share/zabbix/include/classes/api/CApiService.php(1184): CAudit::log()\n#4 /usr/share/zabbix/include/classes/api/services/CUser.php(1583): CApiService::addAuditLogByUser()\n#5 /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php(121): CUser->login()\n#6 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(97): CLocalApiClient->callMethod()\n#7 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(94): CFrontendApiWrapper->callClientMethod()\n#8 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(63): CApiWrapper->callMethod()\n#9 /usr/share/zabbix/include/clas in /usr/share/zabbix/include/classes/api/CAudit.php on line 739, referer:

**Comment by BGmot** [comment]
Check that you have the latest schema, should be this:
```
$ md5sum /usr/share/zabbix/include/schema.inc.php
86ea19a7be6e6bc93a8c95be272d3302  /usr/share/zabbix/include/schema.inc.php
```

**Comment by liyonia** [comment]
:~# md5sum /usr/share/zabbix/include/schema.inc.php
86ea19a7be6e6bc93a8c95be272d3302  /usr/share/zabbix/include/schema.inc.php

same
 PHP Version 7.4.28

**Comment by BGmot** [comment]
What exactly are you trying to do when you get this error in Apache logs?

**Comment by liyonia** [comment]
login with new user ldap

**Comment by BGmot** [comment]
Please confirm you have these match too (from /usr/share/zabbix/ folder):
```
$ md5sum app/controllers/CControllerAuditLogList.php
b0f7d8b857b49264d36064859fac9f3f  app/controllers/CControllerAuditLogList.php
$ md5sum app/controllers/CControllerAuditLogList.php
b0f7d8b857b49264d36064859fac9f3f  app/controllers/CControllerAuditLogList.php
$ md5sum include/classes/api/CAudit.php
46d9eed5e601e22ee55195dbf73f7850  include/classes/api/CAudit.php
$ md5sum include/classes/api/services/CAuditLog.php
c71580ba101cb1618141e231fcb7a42c  include/classes/api/services/CAuditLog.php
$ md5sum include/classes/api/services/CAdUserGroup.php
e76e011ada02c39da853639ef27d3642  include/classes/api/services/CAdUserGroup.php
```

**Comment by liyonia** [comment]
:~# md5sum "/usr/share/zabbix/app/controllers/CControllerAuditLogList.php"
b0f7d8b857b49264d36064859fac9f3f  /usr/share/zabbix/app/controllers/CControllerAuditLogList.php
/usr/share/zabbix# md5sum app/controllers/CControllerAuditLogList.php
b0f7d8b857b49264d36064859fac9f3f  app/controllers/CControllerAuditLogList.php
/usr/share/zabbix# md5sum include/classes/api/CAudit.php
46d9eed5e601e22ee55195dbf73f7850  include/classes/api/CAudit.php
/usr/share/zabbix# md5sum include/classes/api/services/CAuditLog.php
2116d214f9930df45d16a707526eed78  include/classes/api/services/CAuditLog.php
/usr/share/zabbix# md5sum include/classes/api/services/CAdUserGroup.php
e76e011ada02c39da853639ef27d3642  include/classes/api/services/CAdUserGroup.php


CAuditLog.php dosnt match

**Comment by BGmot** [comment]
Thanks! I've found an error in my bg-features-install.sh script -( Don't understand how I missed that as I tested this several times...
Please copy this file manually from https://raw.githubusercontent.com/BGmot/zabbix/release/6.0-bg/ui/include/classes/api/services/CAuditLog.php

**Comment by BGmot** [comment]
Fixed by https://github.com/BGmot/zabbix/commit/35165f51377d3bd5eb785534195d71c4d0085c0b

**Comment by liyonia** [comment]
Mmmmm

PHP Notice:  Undefined index: user.user_medias.0 in /usr/share/zabbix/include/classes/api/CAudit.php on line 733, referer:

PHP Notice:  Undefined index: fields in /usr/share/zabbix/include/classes/api/CAudit.php on line 736, referer: 

PHP Fatal error:  Uncaught TypeError: array_key_exists() expects parameter 2 to be array, null given in /usr/share/zabbix/include/classes/api/CAudit.php:739\nStack trace:\n#0 /usr/share/zabbix/include/classes/api/CAudit.php(813): CAudit::isDefaultValue()\n#1 /usr/share/zabbix/include/classes/api/CAudit.php(587): CAudit::handleAdd()\n#2 /usr/share/zabbix/include/classes/api/CAudit.php(494): CAudit::handleObjectDiff()\n#3 /usr/share/zabbix/include/classes/api/CApiService.php(1184): CAudit::log()\n#4 /usr/share/zabbix/include/classes/api/services/CUser.php(1583): CApiService::addAuditLogByUser()\n#5 /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php(121): CUser->login()\n#6 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(97): CLocalApiClient->callMethod()\n#7 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(94): CFrontendApiWrapper->callClientMethod()\n#8 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(63): CApiWrapper->callMethod()\n#9 /usr/share/zabbix/include/clas in /usr/share/zabbix/include/classes/api/CAudit.php on line 739, referer:

**Comment by BGmot** [comment]
Apparently your LDAP server returns an e-mail address for authenticated user. I have to admit I did not test this field with 6.0.0. It will take some time to reproduce/fix. It's too late already at where I live so I promise to take a look tomorrow. Sorry.

**Comment by liyonia** [comment]
No problem, Thank you in advance.
Me to 5h am

**Comment by BGmot** [comment]
Should be fixed by https://github.com/BGmot/zabbix/commit/b993473bd3d91b977c232a5f1183acff799b3def
Please try new file https://raw.githubusercontent.com/BGmot/zabbix/release/6.0-bg/ui/include/classes/api/services/CUser.php

**Comment by liyonia** [comment]
Yes its work

**Comment by liyonia** [comment]
Hello

Sorry, I still have a small error

PHP Parse error:  syntax error, unexpected '=' in /usr/share/zabbix/app/views/js/administration.userrole.edit.js.php on line 110

**Comment by BGmot** [comment]
Fixed in https://github.com/BGmot/zabbix/commit/5202703940b28f2c4703ecabb172b6a60d22d837
Thanks for reporting!

**Comment by liyonia** [comment]
Thanks
